In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


Creating a Tensor

In [5]:
#using empty
a=torch.empty(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
type(a)

torch.Tensor

In [7]:
#using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#usin ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

rand==Every time you run it, you’ll usually get different numbers because they come from a random number generator.

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.9532, 0.3460, 0.5845],
        [0.2926, 0.3718, 0.9475]])

Where seed comes in
A seed is like setting the “starting point” of the random number generator.
If you set the same seed before generating random numbers, you’ll get the exact same output every run — which is useful for reproducibility.

In [10]:
torch.manual_seed(42)  # set the seed
print(torch.rand(2, 3))

torch.manual_seed(42)  # set it again
print(torch.rand(2, 3))  # same as first output


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange (start, end, step)
print("using arange ->", torch.arange(0,10,2))

# using linspace(start, end, number_of_points)
print("using linspace ->", torch.linspace(0,10,10))

# using eye : Creates a 2D identity matrix of size n×n.
print("using eye ->", torch.eye(5))

# using full (shape, fill_value)
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


all the _like functions in PyTorch (empty_like, zeros_like, full_like, etc.) 

In [13]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
x.shape

torch.Size([2, 3])

torch.empty_like(x)
Creates a new tensor same shape and dtype as x.

The values are uninitialized garbage (whatever was in memory at that location).

Used for fast allocation when you plan to overwrite values immediately.

In [14]:
torch.empty_like(x)


tensor([[8319403537510788960, 2984242175131482971, 7960992446364540285],
        [ 730183621115473249, 2314885530818453536,                 145]])

torch.ones_like(x)
Same shape & dtype as x, but filled with 1s.
Useful for masks or adding a bias of all ones.

In [15]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

torch.rand_like(x, dtype=torch.float32)
Same shape as x, but filled with random numbers uniformly in [0, 1).

The dtype lets you override the original type.
Often used for initializing weights or generating random test data.

In [16]:
torch.rand_like(x, dtype=torch.float32)


tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Tensor Data Types****

In [17]:
# find data type
x.dtype

torch.int64

In [18]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


Mathematical operations

1. Scalar operation

In [21]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [22]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

2. Element wise operation

In [23]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [24]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [25]:
c = torch.tensor([1, -2, 3, -4])

In [26]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [28]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [29]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [30]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [31]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

how torch.clamp works
min=2 → any value less than 2 becomes 2.

max=3 → any value greater than 3 becomes 3.

Values already between [2, 3] stay unchanged.

In [32]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [33]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [34]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18., 14.])

In [35]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)
# mean along row
torch.mean(e, dim=1)

tensor([6.0000, 4.6667])

In [36]:
# median
torch.median(e)
# mean along col
torch.median(e, dim=0)
# mean along row
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([7., 5.]),
indices=tensor([0, 1]))

In [37]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [38]:
# product:Multiplies all elements together.
torch.prod(e) 
# standard deviation Measures how spread out the values are from the mean.By default, uses Bessel’s correction (unbiased=True).
torch.std(e)
# variance : Measures the average squared deviation from the mean.Variance is just (std)².
torch.var(e)
# argmax:Returns the index of the largest value.
torch.argmax(e)
# argmin:Returns the index of the smallest value.
torch.argmin(e)

tensor(3)

4. Matrix operations

In [39]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 4, 9],
        [6, 2, 0]])
tensor([[6, 2],
        [7, 9],
        [7, 3]])


In [40]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[109,  69],
        [ 50,  30]])

In [41]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product :Works only on 1D tensors.
torch.dot(vector1, vector2)

tensor(11)

In [42]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [43]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [44]:
# determinant
torch.det(h)

tensor(-222.)

In [45]:
# inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

5. Comparison operations

In [46]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [47]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i>=j
# less than equal to
i<=j

tensor([[False, False, False],
        [False, False, False]])

6. Special functions

In [48]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [49]:
# log
torch.log(k)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [50]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [51]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [52]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [53]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 3.3535e-04, 4.7426e-02],
        [9.9909e-01, 9.9966e-01, 9.5257e-01]])

In [54]:
# relu
torch.relu(k)

tensor([[0., 1., 1.],
        [7., 9., 4.]])

Inplace Operations

In [55]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [56]:
m.add_(n)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [57]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [58]:
torch.relu(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [59]:
m.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

Copying a Tensor

In [60]:
a = torch.rand(2,3)
a

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [62]:
b = a

In [63]:
b

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [64]:
a[0][0] = 0

In [65]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [66]:
id(a)

135520430316464

In [67]:
id(b)

135520430316464

In [68]:
b = a.clone()

In [69]:
a[0][0] = 10

In [70]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [71]:
id(a)

135520430316464

In [72]:
id(b)

135520430318096